### ISSUE TITLE
HexSticker as a Service

### ISSUE THREAD

**Issue by yosuke-furukawa** [nodeschool/tokyo#10]
このチャンネルでは公開しちゃいますが、年明けからちょっとずつ空き時間を作って友達と一緒に六角形ステッカー専用のサービスを作りました。

![2015-04-06 13 09 41](https://cloud.githubusercontent.com/assets/555645/7000462/609930fa-dc5e-11e4-8b29-f28545846d14.png)

[Hexi](https://hexi.pics) という名前です。オープンβで運用してます。今回のステッカーもこれを元に作る予定です。

https://hexi.pics/items/6fd822b4b2500d5e833c24a01958a249

今回のイベントで初お目見えする予定です。
みなさんも何かイベントする時や六角形ステッカー作りたいときはこのサイトを使ってみてください。

**Comment by tgfjt** [comment]
すごく良いです！

**Comment by watilde** [comment]
ちょういいですね :+1:

**Comment by finnp** [comment]
Please expand this service to Europe, I will send you :dollar: :dollar: :moneybag: :money_with_wings: :yen:

**Comment by yosuke-furukawa** [comment]
@finnp Thank you for your positive feedback!! I am so happy :) 
Currently, we have not translated all pages to English. But we have help page for English users.
please check here. https://hexi.pics/help_en

If you have some troubles, please create an issue here. https://github.com/paeria/Hexi-sayhello
Or ask me [@yosuke_furukawa](https://twitter.com/yosuke_furukawa)
Thanks!!!

**Comment by max-mapper** [comment]
@yosuke-furukawa A M A Z I N G

Do you ship to the US? Also the stickers [here](https://hexi.pics/imgs/help_en/help10.png) look a little larger than the [standard size](http://hexb.in/assets/dimensions.png), but I could be wrong

**Comment by yosuke-furukawa** [comment]
@maxogden Thanks!!
Yes, we can ship to the US. We have already printed stickers as the standard size. Don't worry :D 

![evernote camera roll 20150415 024149](https://cloud.githubusercontent.com/assets/555645/7143285/86b020a2-e319-11e4-87cf-863d811e9ec9.jpg)

![2015-04-14 09 53 38](https://cloud.githubusercontent.com/assets/555645/7143016/cbe6801e-e317-11e4-9817-b02307d2da75.jpg)

**Comment by max-mapper** [comment]
@yosuke-furukawa great! I'll add a link to you from http://hexb.in/ :)

**Comment by max-mapper** [comment]
@yosuke-furukawa also if there are any vector stickers you wanna share on hexb.in (svg, adobe illustrator) feel free to pull request them any time :)

**Comment by sotayamashita** [comment]
@yosuke-furukawa Is it active ?

**Comment by sotayamashita** [comment]
Nobody responds to this issue so I close it.
