### ISSUE TITLE
nodeschool international day: メンター募集

### ISSUE THREAD

**Issue by watilde** [nodeschool/tokyo#16]
## メンター絶賛募集中です :tada:

このIssueは [NodeSchool International Day in Tokyo](http://nodejs.connpass.com/event/14741/) のメンター募集のためのスレです。
[本スレ](https://github.com/nodeschool/tokyo/issues/8) と分けて募集してみています。

---

詳細:
- コメントを頂いたら随時追記しきます。
- イベントの規模的に、10人〜集まると大変助かります・・・！
- 何か質問などありましたら、このスレのコメントか [Gitter](https://gitter.im/nodeschool/nodeschool-japan) の方でお気軽にお声掛け下さい。
- 開始1時間前の **12:30** までに現地集合し、事前の準備や打ち合わせに参加をお願いします :bow:
- 以下のリンクに目を通しておいて頂くようにお願いします
  - [イベントの詳細](https://github.com/nodeschool/international-day/blob/2015/PARTICIPATING.md)
  - [イベントのCoC](https://github.com/nodeschool/international-day/blob/2015/code_of_conduct_ja.md)
- **募集期間: 5/22まで**

---

メンター:
- [x] @kysnm
- [x] @tai2
- [x] @yosuke-furukawa
- [x] @tako-black
- [x] @watilde
- [x] @shuhei 
- [x] @fand
- [x] @ledsun 
- [x] @marocchino 
- [x] @kenchan0130
- [x] @sotayamashita
- [ ] ?????

**Comment by tgfjt** [comment]
参加できそうになく申し訳ないです :cry: 
ちなみに、募集の締め切りはありますか？

**Comment by yosuke-furukawa** [comment]
5/22 です！

**Comment by watilde** [comment]
@tgfjt @yosuke-furukawa 募集期間を **5/22まで** と追記しておきました！

**Comment by yosuke-furukawa** [comment]
ありがとうございます！

**Comment by yosuke-furukawa** [comment]
ちなみに、デフォルトで入ってると僕が思っている、

@sotayamashita san
@tako-black san
@ledsun san 
@watilde san 

たちは空いてるんですかね。

**Comment by kohei-takata** [comment]
@yosuke-furukawa 空いてます！メンターやります！

**Comment by watilde** [comment]
@yosuke-furukawa さんと@tako-black さんをリストに追加させて頂きました！
自分を入れるの忘れてたので同じく追加しましたー。

**Comment by shuhei** [comment]
前回に引き続き、メンターやらせてください！

**Comment by watilde** [comment]
@shuhei 追加させて頂きました！よろしくお願いします :smiley_cat:

**Comment by fand** [comment]
はじめまして fand(twitter @amagitakayosi) と申します、Node学園祭とか何回か参加しました
今回ぜひメンターなり会場の手伝いなりやらせてくれませんかっｌ

**Comment by ledsun** [comment]
メンターやります。
メンターは12:30集合と思っています。合っていますか？

**Comment by tgfjt** [comment]
@fand @ledsun 
ありがとうございます！追加致しました。

**Comment by marocchino** [comment]
メンターやります。 'ㅁ'/

**Comment by tgfjt** [comment]
@marocchino 追加致しました！

**Comment by watilde** [comment]
@ledsun そうですね、今回も1時間前集合で大丈夫だと思います！

> メンターは12:30集合と思っています。合っていますか？

説明文に追記しておきますね:)

**Comment by kenchan0130** [comment]
引き続きお手伝いさせてください！

**Comment by watilde** [comment]
@kenchan0130 ありがとうございます。よろしくお願いします！

**Comment by ledsun** [comment]
メンターはconnpassで参加登録しない方が良いですか？

**Comment by sotayamashita** [comment]
@ledsun connpassで参加登録する必要はありません。

**Comment by sotayamashita** [comment]
遅れましたが参加可能です。ただ17時ごろに抜けなくてはいけません。自分で追加しときました

**Comment by sotayamashita** [comment]
イベントが終了したので閉じます
