### ISSUE TITLE
nodeschool東京のメンバーになって東京でのnodeschoolを開催を協力していただける方募集

### ISSUE THREAD

**Issue by sotayamashita** [nodeschool/tokyo#2]

**Comment by ledsun** [comment]
興味あります。どのような協力をしたらよいでしょうか？

**Comment by nishimurakaori** [comment]
技術面では力になれませんが、おやつを買う係とかなら協力できます！

**Comment by sotayamashita** [comment]
@ledsun 興味をもっていただきありがとうございます。issueにあるように大阪で定期的に行われているnodeschool Tokyoのワークショップの開催に協力していただけるかたを募集しております。

**Comment by sotayamashita** [comment]
@nishimurakaori コメントありがとうございます！皆さんでたのしくやっていければと思いますのでどんな形であっても協力していただけるとありがたいです。

**Comment by watilde** [comment]
東京での開催、いいですね。
お手伝いさせてください :smiley_cat:

**Comment by sotayamashita** [comment]
@watilde ありがとうございます！！皆さんで一緒にできたらとおもいます。ちなみにnodejs学園とかと協力してやるとか、どのように開催するのがいいと思われますか？

**Comment by sotayamashita** [comment]
nodeschool東京の開催においてみなさんなにかアイデアはありますか？

**Comment by watilde** [comment]
@sota0805 開催日を固め、会場とメンターを募い、そのキャパに合わせてイベントを立てて
Node.js | io.js 日本ユーザーグループのメーリスで告知を行う。

みたいな流れをイメージしてました。
こちら http://nodejs.connpass.com/ に相乗りさせて頂けると進めやすそうですね。

**Comment by yosuke-furukawa** [comment]
|дﾟ)ﾁﾗｯ

**Comment by yosuke-furukawa** [comment]
4月にNode学園の入学式的な奴をやろうかと思ってましたが、実際に日付の具体的な所が抑えられれば、DeNAで会場提供できますー！

**Comment by sotayamashita** [comment]
@watilde 

> 開催日を固め、会場とメンターを募い、そのキャパに合わせてイベントを立てて
> Node.js | io.js 日本ユーザーグループのメーリスで告知を行う。

この辺のイベント開く際の流れをやったことがないのですが、詳しいですか？

> こちら http://nodejs.connpass.com/ に相乗りさせて頂けると進めやすそうですね。

なるほど・・・

**Comment by sotayamashita** [comment]
@yosuke-furukawa 

> 4月にNode学園の入学式的な奴をやろうかと思ってましたが、実際に日付の具体的な所が抑えられれば、DeNAで会場提供できますー！

おお、ありがとうございます！入学式的なところでこれをnodeschool使って勉強しようみたいな流れも作れるとありがたいです

**Comment by sotayamashita** [comment]
ちなみにCyberAgentも会場提供できると思います。

**Comment by yosuke-furukawa** [comment]
CA様でもDeNAでもどちらでも良いかと思います！
いつ頃開催か、人数規模、場所、懇親会の有無、等を決めてもらえたら、後はconnpassとかで開催案内するだけかと。

もちろん、node学園のconnpassで開催案内も作れます。
定期的に開催する予定であれば、 nodejs.connpass.com の管理者権限もお渡しできますー。

**Comment by sotayamashita** [comment]
@yosuke-furukawa 

> いつ頃開催か、人数規模、場所、懇親会の有無、等を決めてもらえたら、後はconnpassとかで開催案内するだけかと。

了解です。この辺を一旦 @martinheidegger とも話してみます。

> もちろん、node学園のconnpassで開催案内も作れます。
> 定期的に開催する予定であれば、 nodejs.connpass.com の管理者権限もお渡しできますー。

了解です。

**Comment by yosuke-furukawa** [comment]
どれ位人来ますかね。ちなみにうちだと150人くらいは入れます。
やるのって、learnyounodeとかの所謂nodeschoolってやつですよね？

**Comment by e-jigsaw** [comment]
ノ

**Comment by watilde** [comment]
Osakaの参加者数を見るに、
30 ~ 50人くらいで見てみるとかどうでしょうか
https://nodeschool.doorkeeper.jp/

**Comment by martinheidegger** [comment]
Nodeschool の doorkeeper は東京のNodeSchoolのためにも使えます！

**Comment by yosuke-furukawa** [comment]
https://nodeschool.doorkeeper.jp/ こっちでも良さそう！
まぁいずれにせよ、場所や講師、なんでも手伝いますー

**Comment by sotayamashita** [comment]
@martinheidegger 分かりました！

**Comment by sotayamashita** [comment]
@yosuke-furukawa ありがとうございます！

**Comment by tai2** [comment]
手伝いますよ。

**Comment by yosuke-furukawa** [comment]
@sotayamashita 

せっかくだから結構大きめにやりませんか？なんでもバックアップするので。
CA様で4月に150 - 300名の会場とかって抑えられるならそこでやりたくて、
うちだと 150 名は入るけどそれ以上は入らないので。

Node学園の入学式っていう形でやれるといいかなと思っています。

**Comment by e-jigsaw** [comment]
入学式 +1

**Comment by sotayamashita** [comment]
@yosuke-furukawa 

CAでできるかどうかを確認してみます。ちなみにNode学園の入学式のコンテンツってどんなかんじを想定していますか？というのもその中でどのようにNodeSchoolを行うのかについても考えたいので・・

**Comment by yosuke-furukawa** [comment]
こんな感じのイメージです！

土日の夕方から集まる 15:00 位？
2時間くらいガッツリ時間取って nodeschool のいくつかの項目にチャレンジしてもらう。
一個でも終わったら入学成立、ステッカー配る。（このへんのスケジュール感、一回しかやったこと無いので、2時間では少ないとかあれば教えて下さい。）

17:00 からは LT大会で自分が今やってるNode.jsの事をちょろちょろっと話してもらう。
全体で30分くらいかな。

終わったら懇親会 18時〜とか。

ちなみにステッカー周りはちょっと当てがあるので、任せてくれて構いません。

タイムスケジュール的に言うと
- 15:00 - 17:00 NodeSchool in Tokyo 2hour
- 17:00 - 17:30 LT 大会 (5分 x 6)
- 17:30 - 19:00 (懇親会的な)

**Comment by sotayamashita** [comment]
@yosuke-furukawa スケジュールのアイデアありがとうございます。

現在CAを会場として使えるか調整中です。

**Comment by martinheidegger** [comment]
@yosuke-furukawa と @tai2 と @sotayamashita はdoorkeeperの管理者にインバイトしました。

**Comment by tai2** [comment]
了解ですー。

@sotayamashita 雑用とかメンターでの協力ができると思います。必要でしたら言ってください。

**Comment by sotayamashita** [comment]
@martinheidegger  確認しました。ありがとうございます

@tai2 ありがとうございます。

**Comment by watilde** [comment]
イベントの開催は、こちらも参照したほうが良さそうですね
http://nodeschool.io/host.html

**Comment by yosuke-furukawa** [comment]
こちらどうなりました？？

**Comment by sotayamashita** [comment]
@yosuke-furukawa 連絡が遅くなってしまって申し訳ありません。CAが新卒の研修などいつものところとの調整がつかずにCAを使用することが難しいです。

**Comment by ledsun** [comment]
雑用でも、メンターでもお手伝いします。

**Comment by sotayamashita** [comment]
@ledsun ありがとうございます。4月12日にイベントを開催する予定ですのでその際に声をかけさせていただくかもしれません。

**Comment by kohei-takata** [comment]
お手伝いします！イベント開催の際も協力できます！

**Comment by yosuke-furukawa** [comment]
ここにも書いておきます。

イベント管理ページを作っています。
http://connpass.com/event/13182/edit/

管理者になるとメンターの追加とかページの編集とか好きにできるようになると思います。
@sotayamashita ちょっと探したんですが、 connpassの id が分かりませんでした。
connpass上でのidを教えてくれれば追加しておきます。

**Comment by sotayamashita** [comment]
@yosuke-furukawa 

> イベント管理ページを作っています。
> http://connpass.com/event/13182/edit/

ありがとうございます。確認しました。

> connpass上でのidを教えてくれれば追加しておきます。
> idはsota0805です。お願いします

**Comment by yosuke-furukawa** [comment]
これいつ頃公開されますか? 
そろそろ公開しないとスケジュール調整が難しくなりそうな人がいそうな気がします。

**Comment by sotayamashita** [comment]
@yosuke-furukawa 公開の方していただければと思います。よろしくお願い致します

**Comment by yosuke-furukawa** [comment]
@sotayamashita 
これって、今回やるカリキュラムはこれでOKですか？？
- javascripting (JavaScriptの基礎)
- learnyounode (Node.jsの基礎)
- how to npm (npmの基礎)
- levelmeup (LevelDBの基礎)

もしも他にもあれば教えて下さい。僕は個人的に count-es6 のbabel版作ろうかと思ってました。

**Comment by tgfjt** [comment]
当日他用のため何もできないのですが、

代わりにこちらへの登録はしておきますね！
http://nodeschool.io/host.html

Babelいいですね:+1:

追記: 登録完了しました。

**Comment by sotayamashita** [comment]
@yosuke-furukawa 

> - javascripting (JavaScriptの基礎)
> - learnyounode (Node.jsの基礎)
> - how to npm (npmの基礎)

上記に関してはこのカリキュラムでいいと思っております。
levelmeup(LevelDBの基礎)に関しては他のと少し異なるので
どうかなと思っていました。

> count-es6 のbabel版作ろうかと思ってました。

babelいいですね。もしそれが完成しましたら、
levelmeup(LevelDBの基礎)の代わりにしたいです。

**Comment by sotayamashita** [comment]
@tgfjt ありがとうございます。

**Comment by kohei-takata** [comment]
ちょっと上にも書いてますが、メンターやります！

**Comment by myakura** [comment]
こんばんは。nodeschool東京でできたらいいなーと思ってたので、計画されてる方がいてうれしいです！
ほかの3つはやったことないのですが、learnyounodeであれば2年くらい前にやったので、メンターできるかと思いますー

**Comment by kysnm** [comment]
あまり自信はないですが、足りなさそうでしたらメンターやります

**Comment by tgfjt** [comment]
スケジュール都合ついたので自分もメンターやります！

**Comment by sotayamashita** [comment]
@tako-black 改めてお願いします。

@myakura ありがとうございます。お願いします。

@kysnm ありがとうございます

@tgfjt おお！ありがとうございます。

**Comment by kaidouji85** [comment]
LTの申し込みをします。
内容は私が趣味で作っている、node.js製対戦ゲームについてです。

**Comment by YukiMiyatake** [comment]
よかったら手伝わせて下さい。

**Comment by YukiMiyatake** [comment]
nodeは2回程小さいものを作った程度で
何故かC++でのサーバ構築だらけですが、メンターやりたいです。

**Comment by yosuke-furukawa** [comment]
@YukiMiyatake san connpass の id を教えて下さいー。

**Comment by YukiMiyatake** [comment]
@yosuke-furukawa 
http://connpass.com/user/Yuki/
これでよいでしょうか

**Comment by axross** [comment]
メンター的な役割でお手伝いさせて下さいー。参加申し込みもしているので、外れた方がよければ参加の方は外しておきます。

**Comment by yosuke-furukawa** [comment]
@YukiMiyatake 
@axross 追加しました。メンターなので、参加者からは外れておいて下さい。

**Comment by axross** [comment]
@yosuke-furukawa
了解です。

**Comment by shuhei** [comment]
すごい申し込みの数ですね！メンター枠がまだ空いていればお手伝いさせてください。ES6/babel も仕事で使っているので何とかなると思います。

**Comment by k2wanko** [comment]
まだ　メンター募集されていたら
僕にもお手伝いさせていただけないでしょうか？

**Comment by sotayamashita** [comment]
@myakura , @tako-black 

メンターになってくださりありがとうございます。お手数ですがメンターなので、参加者からは外れていただいてもよろしいでしょうか？

**Comment by yosuke-furukawa** [comment]
@shuhei @k2wanko 
メンターとして追加しましたー。

**Comment by kohei-takata** [comment]
@sotayamashita キャンセルしました！

**Comment by muddydixon** [comment]
メンター募集まだしてるかな？
役立たずかもしれませんが・・・

**Comment by yosuke-furukawa** [comment]
@muddydixon 追加しました。
今メンター16人ですね。

**Comment by niryuu** [comment]
ここ 3 ヶ月は Python でしたが，0.10系,  express 3 と sails でプロジェクトやってました．
今度は dirty code のリファクタなどすることになりそうなので，初心者のメンターをやることで学ぶことがあればと思い，ぜひ参加したいです．
非エンジニアに Android と Linux の講師をしたことがあり，それぞれ5人に1人くらいそっち系の職に就けたので，そこそこ初心者に教える力はあると思います．

**Comment by yosuke-furukawa** [comment]
@niryuu さん、追加しました！

**Comment by tkd55** [comment]
メンター募集されていますでしょうか？
微力ではありますが、お手伝いさせてください。

**Comment by yosuke-furukawa** [comment]
@tkd55
大丈夫です！connpassのidを教えてください！

**Comment by tkd55** [comment]
takeda_tomomichi
にまります！よろしくお願いします！

**Comment by tkd55** [comment]
@yosuke-furukawa
takeda_tomomichi
にまります！よろしくお願いします！

**Comment by kidach1** [comment]
よろしければお手伝いさせてください。
一応node使いつつ、ES6だとPromise、Generatorあたりを実用しています。
connpass idはkidachi_です。

**Comment by yosuke-furukawa** [comment]
@tkd55 @kidach1 
メンターに追加しました。よろしくお願いいたします。

**Comment by shimbaco** [comment]
LT参加希望です!
最近Node.jsの習作として簡単な画像変換サーバを作ったので、その紹介をさせて貰えたらと思います。
https://github.com/bojovs/tombo

ConnpassのIDは bojovs ([http://connpass.com/user/bojovs/](http://connpass.com/user/bojovs/))です。
よろしくお願いします。

**Comment by kenchan0130** [comment]
まだメンター募集されていますでしょうか。
よろしければお手伝いさせてください。

**Comment by sotayamashita** [comment]
メンターの皆様当日やるワークショップは以下のリンクにあるのでぜひ一度やってみてください！！

https://github.com/nodeschool-jp/translators

**Comment by kamiyam** [comment]
あ、メンター募集こちらでされていたのですね。
まだ募集していますか？

**Comment by moomoo-ya** [comment]
LT参加大丈夫でしょうか？
内容は
  LoopBackを使った極初歩的なAPIとSwiftで作るオシャレアプリ（）
でやりたいと思います。

Connpass のIDは isamu_suzuki_54 です。

**Comment by yosuke-furukawa** [comment]
すごい増えてた！ちょっとお待ちください。

**Comment by hiro93n** [comment]
LT参加、もし枠が空いていたら参加したいです。
express触り始めて、かつちゃんとコードを書き始めてまだ２ヶ月くらいなのですが
教えてもらいつつ一つサービスをリリースしたので
こわくない！ディレクターがexpressではじめる新規開発、的なテーマでやりたいと思います。

ConnpassのIDはhiro93nです。

**Comment by yosuke-furukawa** [comment]
@bojovs @moomoo-ya @hiro93n LT枠に追加しました。
@kenchan0130 @kamiyam メンター枠に追加しました。

**Comment by yosuke-furukawa** [comment]
LTはあと一つで、メンターはあと4人くらいですかね。メンターがめちゃくちゃ多い。

**Comment by kamiyam** [comment]
@yosuke-furukawa ありがとうございます。よろしくお願いします！

**Comment by hiro93n** [comment]
@yosuke-furukawa ありがとうございます！

**Comment by shimbaco** [comment]
@yosuke-furukawa ありがとうございますー!

**Comment by kamiyam** [comment]
あ、参加枠に入っているのですが、抜けた方が良いですよね？

**Comment by yosuke-furukawa** [comment]
お願いします @kamiyam

**Comment by kamiyam** [comment]
@yosuke-furukawa 了解です

**Comment by tgfjt** [comment]
@tai2 さん筆頭に、 how-to-npm の翻訳していただきましたので、publish しました。
`npm i -g how-to-npm-jp` でインストール出来るようになりましたので、ぜひお試しくださいませ。

**Comment by sotayamashita** [comment]
:+1:  https://github.com/nodeschool-ja/how-to-npm-jp

**Comment by TakaakiItagaki** [comment]
コメント失礼いたします。LTさせていただきたいのですがまだ枠は残っておりますでしょうか？

**Comment by watilde** [comment]
@TakaakiItagaki レスポンスが遅れてすみません、LT枠として追加させて頂きました！
http://nodejs.connpass.com/event/13182/

タイトルは決まっていますでしょうか？

**Comment by yosuke-furukawa** [comment]
一応、 tower-of-babel という名前の babel tutorial 作成してみましたー。メンターの方々、お時間あればやってみてください。何か問題があれば言ってくれれば修正します。
ちなみに時間の都合上日本語だけです。。。

**Comment by tai2** [comment]
おーすばらしい!! やるのがたのしみです! 明日やってみます!

**Comment by yosuke-furukawa** [comment]
https://github.com/yosuke-furukawa/tower-of-babel あ、 tower-of-babelはコチラです！

**Comment by yosuke-furukawa** [comment]
当日ですが、13:30 にスタッフ/メンターは集合しましょう。
受付の段取りとか決めておけると幸いです。

**Comment by tgfjt** [comment]
了解でございます。

**Comment by ledsun** [comment]
:ok:

**Comment by tai2** [comment]
:ok_hand:

**Comment by kohei-takata** [comment]
:ok:

**Comment by kysnm** [comment]
:octocat:

**Comment by sotayamashita** [comment]
:ok:

**Comment by martinheidegger** [comment]
:+1:

**Comment by k2wanko** [comment]
:ok:

**Comment by applideveloper** [comment]
メンターまだ募集してますでしょうか？

**Comment by tkd55** [comment]
都合が悪くなりお手伝い出来なくなりました。
申し訳ないです。

**Comment by yosuke-furukawa** [comment]
こんな日に限って山手線と京浜東北線が止まるとは。
ついてないですが、一応時間通りに来れる方がいれば来れる人達だけでもいいのでやりましょう。13:30に開始する予定なのでよろしくお願いします。

**Comment by k2wanko** [comment]
:ok:

**Comment by kamiyam** [comment]
:ok_hand:
早めに出て正解でした。界隈で予習してます。

**Comment by kenchan0130** [comment]
:ok_woman:
