### ISSUE TITLE
11/28 NodeSchool(場所:レバレージーズさん) メンター募集

### ISSUE THREAD

**Issue by kohei-takata** [nodeschool/tokyo#24]
今週末の学園祭でNodeSchoolが行われますが、今月末にもレバレージーズさん（teratail）とNodeSchoolを開催することになりました！

つきましてはメンターをやっていただける方を募集させていただきたいと思います！
参加者が30〜50名とのことですので、5人ほどかなと思っております。
メンターをやっていただける方はこのIssueかgitterで僕までご連絡いただけると嬉しいです！
イベント詳細は以下の通りです。

日時:2015/11/28(土) 午後〜
場所:レバレージーズさん（ヒカリエ17階）
内容:NodeSchoolと、イベント後もNode.jsで開発を継続するためのコンテンツ（未定）

---

メンター
@kohei-takata
@sotayamashita さん
@marocchino さん
@ledsun さん
@kenchan0130 さん

**Comment by sotayamashita** [comment]
@tako-black 参加できます！

**Comment by kohei-takata** [comment]
@sotayamashita ありがとうございます！

**Comment by marocchino** [comment]
@tako-black 参加できます。

**Comment by kohei-takata** [comment]
@marocchino ありがとうございます！！

**Comment by ledsun** [comment]
@tako-black 参加できます！

**Comment by kohei-takata** [comment]
@ledsun ありがとうございます！

**Comment by kenchan0130** [comment]
@tako-black
参加できます！！

**Comment by kohei-takata** [comment]
@kenchan0130 ありがとうございます！！！！！

**Comment by kohei-takata** [comment]
@sotayamashita さん
@marocchino さん
@ledsun さん
@kenchan0130 さん

改めてメンターを引き受けてくださってありがとうございます！
当日のイベントページは[こちら](http://connpass.com/event/22167/)です。
当日は12:50までに渋谷ヒカリエ11階にお越しください！
遅れる場合などは上記のURLの「会場への入場に関して」を参照してください。
また何か質問など有りましたら僕までよろしくお願いします！
それでは当日はよろしくお願いします！

**Comment by sotayamashita** [comment]
@kohei-takata すいません。自分の twitter は @sotayamashite ではなく @sota0805 です。

https://twitter.com/sota0805

**Comment by kohei-takata** [comment]
@sotayamashita 
修正しました！すみません！

**Comment by sotayamashita** [comment]
@kohei-takata わざわざありがとうございます！

**Comment by kohei-takata** [comment]
@sotayamashita さん
@marocchino さん
@ledsun さん
@kenchan0130 さん

リマインダです！
イベントページは[こちら](http://connpass.com/event/22167/)です。
明日は12:50までに渋谷ヒカリエ11階にお越しください！
遅れる場合などは上記のURLの「会場への入場に関して」を参照してください。
それでは明日どうぞよろしくお願いします！

**Comment by kohei-takata** [comment]
参加してくださったメンターの皆さん、ありがとうございました！
