### ISSUE TITLE
3/6 NodeSchool Tokyo for Girls(場所:レバレジーズさん) メンター募集

### ISSUE THREAD

**Issue by kohei-takata** [nodeschool/tokyo#27]
3月にもレバレジーズさんとNodeSchoolを開催することになりました！
今回は初の試みとして、参加者が女性限定のNodeSchoolとなっています。
今年も、JSに入門したいと思っている方の参加障壁を下げていけたらなと思います。

つきましてはメンターをやっていただける方を募集させていただきたいと思います！
参加者が30〜50名とのことですので、5人ほどかなと思っております。
メンターをやっていただける方はこのIssueかgitterで僕までご連絡いただけると嬉しいです！
イベント詳細は[こちら](http://nodejs.connpass.com/event/25165/)の通りです。

**Comment by kysnm** [comment]
微力ながらお手伝い出来ればと。希望者が多そうなら遠慮します… :sweat_drops:

**Comment by tgfjt** [comment]
不在のため参加できず。。。:bow:

**Comment by ledsun** [comment]
参加できます。
connpassのメンター枠に登録した方が良いですか？

**Comment by kohei-takata** [comment]
@kysnm 
@ledsun 
ありがとうございます！！
一応[こちら](http://nodejs.connpass.com/event/25165/)からメンター枠で登録をお願いいたします！

@tgfjt 
ご連絡ありがとうございます！
ぜひ次回はよろしくお願いいたします！

**Comment by sotayamashita** [comment]
こちらイベントが終了したので close します
