### ISSUE TITLE
nodeschool international day: メンター募集

### ISSUE THREAD

**Issue by sotayamashita** [nodeschool/tokyo#29]
## メンター絶賛募集中です :tada: :turtle: :rocket: 

このIssueは [NodeSchool International Day Tokyo](http://eventdots.jp/event/588575) のメンター募集のためのスレです。

---

詳細:
- コメントを頂いたら随時追記しきます。
- イベントの規模的に、10人〜集まると大変助かります・・・！
- 何か質問などありましたら、このスレのコメントか [Gitter](https://gitter.im/nodeschool/nodeschool-japan) の方でお気軽にお声掛け下さい。
- 開始1時間前の **13:30** までに現地集合し、事前の準備や打ち合わせに参加をお願いします :bow:
- 以下のリンクに目を通しておいて頂くようにお願いします
  - [イベントの詳細](https://github.com/nodeschool/international-day/blob/2016/PARTICIPATING.md)
  - [イベントのCoC](https://github.com/nodeschool/international-day/blob/2016/code_of_conduct_ja.md)
- **募集期間: 5/20まで**

---

当日やるワークショップ：
- https://github.com/sethvincent/javascripting
- https://github.com/workshopper/learnyounode
- https://github.com/npm/how-to-npm
- https://github.com/yosuke-furukawa/tower-of-babel
- https://github.com/kohei-takata/learnyoureact
- https://github.com/yosuke-furukawa/electronica

---

メンター:
- [x] @yosuke-furukawa
- [x] @kohei-takata 
- [x] @sotayamashita
- [x] @kubosho 
- [x] @shuhei 
- [x] @yoshuawuyts 
- [x] @ledsun

**Comment by kubosho** [comment]
メンターやってみたいです（もしメンターをやることになった場合は初めてなのでいろいろと不安ですが…）
イベント詳細やCoCには目を通してあります。

**Comment by shuhei** [comment]
メンターやらせてください！ 🎉

**Comment by sotayamashita** [comment]
@kubosho さん @shuhei さんありがとうございます。追加させて頂きます

**Comment by kubosho** [comment]
ありがとうございます！当日使う教材としては以下の6つでいいでしょうか？
https://github.com/sethvincent/javascripting
https://github.com/workshopper/learnyounode
https://github.com/npm/how-to-npm
https://github.com/yosuke-furukawa/tower-of-babel
https://github.com/kohei-takata/learnyoureact
https://github.com/yosuke-furukawa/electronica

**Comment by sotayamashita** [comment]
@kubosho 合っております

**Comment by kubosho** [comment]
@sotayamashita
ありがとうございます。おさらいの意味で当日までに上記リポジトリで勉強しておこうと思います。

**Comment by yoshuawuyts** [comment]
Hey, I'm in town this week; I'd be happy to help out (in English) if you'll have me :tada:

**Comment by sotayamashita** [comment]
@yoshuawuyts I appreciate it. Please join our international day meetup !!

**Comment by ledsun** [comment]
メンターやります。

**Comment by sotayamashita** [comment]
@ledsun ありがとうございます。追加させていただきます。

**Comment by yoshuawuyts** [comment]
わーい! :tada:
Oh ps, I noticed the website isn't updated with the latest event - http://nodeschool.io/tokyo/

**Comment by sotayamashita** [comment]
@yoshuawuyts I am doing. 😄

**Comment by tgfjt** [comment]
Updated! http://nodeschool.io/tokyo/

ありがとうございます！
@sotayamashita 
@watilde 

でも残念ながら予定があり、メンターできませぬ 😢

**Comment by sotayamashita** [comment]
@tgfjt ページの確認とマージありがとうございました。 :bow:

**Comment by yoshuawuyts** [comment]
@tgfjt 悲しい 😭

**Comment by tgfjt** [comment]
終わってそうなので閉じますね〜
ありがとうございました！ 🎉 :bow:
