### ISSUE TITLE
東京Node学園祭2016 1日目：メンター募集

### ISSUE THREAD

**Issue by sotayamashita** [nodeschool/tokyo#33]
# メンター絶賛募集中です :tada: :turtle: :rocket:

> このIssueは [東京Node学園祭2016 1日目](http://nodejs.connpass.com/event/43011/) のメンター募集のためのスレです。
## 詳細
- コメントを頂いたら随時追記しきます。
- イベントの規模的に、10人ほど集まると大変助かります・・・！:bow:
-  何か質問などありましたら、このスレのコメントか [Gitter](https://gitter.im/nodeschool/nodeschool-japan) の方でお気軽にお声掛け下さい。
## 事前準備

**行動規範に目を通す**
[CoC](http://nodefest.jp/2016/coc.html) とは行動規範で事前に一通り読んでいただいて、当日は守っていただければと思います。

**当日やる予定のワークショップを確認する**
それから下のワークショップ達は事前にやっておくと当日スムーズにメンターが出来るかと思います。
答えが分かるのはもちろん、難易度や詰まりやすい箇所、当日されそうな質問が想定できるからです。
必須ではありません。
-  https://github.com/sethvincent/javascripting
-  https://github.com/workshopper/learnyounode
-  https://github.com/npm/how-to-npm
-  https://github.com/yosuke-furukawa/tower-of-babel
-  https://github.com/kohei-takata/learnyoureact
-  https://github.com/yosuke-furukawa/electronica

## 参照
- [Code And Learn at NodeFest 2016 #58](https://github.com/nodejs/code-and-learn/issues/58)
- [Nodeへのコード貢献の仕方 | スライド](https://speakerdeck.com/shigeki/nodehefalse-kodogong-xian-falseshi-fang)
- [Nodeへのコード貢献の仕方 | GitHub](https://github.com/shigeki/code_and_learn_nodefest_tokyo_2016)

## スタッフ以外で協力していただけるメンターの方々
- @shigeki
- @kentrino
- @dominhhai
- @qsona 
- @abouthiroppy

**Comment by tgfjt** [comment]
✋

**Comment by sotayamashita** [comment]
@tgfjt ありがとうございます。スタッフの方は、メンターの兼務をお願いします :smile:

**Comment by marocchino** [comment]
✋

**Comment by kubosho** [comment]
✋

**Comment by shigeki** [comment]
Code + Learn 中心にメンターやります。

**Comment by sotayamashita** [comment]
@shigeki 大変たすかります。ありがとうございます :bow: :bow:

**Comment by shigeki** [comment]
@sotayamashita 具体的な話ってどこでしたらいいですかね？ 
取り急ぎ  CONTRIBUTING.md の和訳 done です。 https://gist.github.com/shigeki/873ff5b0c79dc4787691411a91630b3b  /CC @yosuke-furukawa

**Comment by sotayamashita** [comment]
@shigeki 翻訳していただきありがとうございます。具体的な話は Node/iojs-jp の#nodefest チャンネルでしようと思うのですが、こちらのチャンネルを見ることは可能でしょうか？

**Comment by shigeki** [comment]
@sotayamashita slack channelですよね。登録してあるんですが 2FA の設定してなくてログインできなくなってました。HELP見ると Team の Admin から私のアカウントの2FA設定外して対応するようにと書いてありましたが、対応していただくことは可能でしょうか？

**Comment by kentrino** [comment]
メンター希望致します

**Comment by sotayamashita** [comment]
@shigeki 返事が遅くなってしまって申し訳ありません。Slack だと登録していない方もいてコミュニケーションがややこしくなるのでこちらで話し合えればと思います。

**Comment by kentrino** [comment]
@sotayamashita 参加にあたって事前準備等はございますでしょうか？  
連絡用のE-mailアドレスを含んだprivateリポジトリに招待いたしましたので、ご確認いただけると幸いです。

**Comment by sotayamashita** [comment]
@kentrino 

> 参加にあたって事前準備等はございますでしょうか？
> 以下の CoC とワークショップを人通りやって頂ければと思います。
- [イベントのCoC](http://nodefest.jp/2016/coc.html)
- https://github.com/sethvincent/javascripting
- https://github.com/workshopper/learnyounode
- https://github.com/npm/how-to-npm
- https://github.com/yosuke-furukawa/tower-of-babel
- https://github.com/kohei-takata/learnyoureact
- https://github.com/yosuke-furukawa/electronica

> 連絡用のE-mailアドレスを含んだprivateリポジトリに招待いたしましたので、ご確認いただけると幸いです。

レポジトリへの招待ありがとうございます。ただ基本的にすべてのやりとりはここで行うので、なにかあればこちらにコメントいただければと思います。

**Comment by kohei-takata** [comment]
@kentrino @sotayamashita 
すみませんちょっと補足しますね、CoCっていうのは行動規範なので、事前に一通り読んでいただいて、
当日は守っていただければと思います。

それから下のワークショップ達は事前にやっておくと当日スムーズにメンターが出来るかと思います。
答えが分かるのはもちろん、難易度や詰まりやすい箇所、当日されそうな質問が想定できるからです。
必須ではありません。

**Comment by sotayamashita** [comment]
@kohei-takata 言葉がたらずすいません。詳細にも書き足しておきます。何か不備がある場合などは追加で編集していただければと思います。

**Comment by kohei-takata** [comment]
@sotayamashita いえいえ！ありがとうございます！

**Comment by kentrino** [comment]
@kohei-takata @sotayamashita 了解しました。ありがとうございます！

**Comment by dominhhai** [comment]
まだ募集中ですか？

**Comment by kohei-takata** [comment]
@dominhhai 募集しております！是非お願いいたします！

**Comment by qsona** [comment]
こんばんは、
午前のNodeDiscussionだけはどううううしても参加したいのですが><、
午後からだけでももし可能でしたら、メンターをさせていただこうと思うのですが、いかがでしょうか。
javascriptingとlearnyounodeに関しては手助けできると思います。

**Comment by sotayamashita** [comment]
@dominhhai ありがとうございます。助かります

**Comment by qsona** [comment]
@sotayamashita あ、すみません、僕へのレスだと思うのですが、 @dominhhai さんとは別の者です><。 こちらこそ貴重な機会をありがとうございます。

**Comment by sotayamashita** [comment]
@qsona 

> > @dominhhai ありがとうございます。助かります  
> 
> あ、すみません、僕へのレスだと思うのですが、 @dominhhai さんとは別の者です><   

こちらは @dominhhai への返信をしたつもりでした。わかりづらくて申し訳ありません.

**Comment by sotayamashita** [comment]
@qsona 

> 午後からだけでももし可能でしたら、メンターをさせていただこうと思うのですが、いかがでしょうか。
> javascriptingとlearnyounodeに関しては手助けできると思います。

こちら検討させてください。本日中には返信させていただきます。
cc/ @kohei-takata

**Comment by qsona** [comment]
承知しました、大変失礼いたしました。面倒かけてしまったようですみません。。(午前中のためにチケット買ったので、午後は基本的にフリーなので、もしお手伝いできればという感じでした。)ちなみに、javascriptingとlearnyounodeの2つ以外は専門的な知識はそこまでないという意図でしたが、もしお手伝いさせて頂ければワークショップのレベルまでは準備しておきます。

**Comment by sotayamashita** [comment]
@qsona 
ややこしくしてしまって申し訳ありません。午後からで問題ないので参加して頂ければ幸いです。:bow:

**Comment by qsona** [comment]
はい、ありがとうございます! よろしくお願いします。

**Comment by hiroppy** [comment]
メンターやります。

**Comment by sotayamashita** [comment]
@qsona 
@abouthiroppy 

当日はよろしくお願い致します。 :bow:

**Comment by shigeki** [comment]
Code and Learn ですが、どこまで準備されているのかわからなかったので、一通りの資料を用意しました。
1時間半しかないので、事前にバグや修正箇所を持ってないといきなり本番へのPRまで行き着くのは難しいんじゃないかと思います。なので初めての人用にPRのハンズオン repository を作ってあります。

資料: https://speakerdeck.com/shigeki/nodehefalse-kodogong-xian-falseshi-fang
資料repository: https://github.com/shigeki/code_and_learn_nodefest_tokyo_2016
ハンズオン用Repository: https://github.com/shigeki/node_testpr

別のコンテンツが用意されているのか、これで構わないのか、確認をお願いしたいです。

**Comment by yoshuawuyts** [comment]
if you need more hands; @watson, @mafintosh and me will be around and can help out 🎉

**Comment by tgfjt** [comment]
Code and Learn は古川さんしか分からないのかな…

**Comment by sotayamashita** [comment]
@shigeki 
cc:/ @tgfjt 

> 事前にバグや修正箇所を持ってないといきなり本番へのPRまで行き着くのは難しいんじゃないかと思います

只今 PR できるところについてはこちらでやり取りされています。
https://github.com/nodejs/code-and-learn/issues/58

> なので初めての人用にPRのハンズオン repository を作ってあります。

ありがとうございます :bow:

**Comment by shigeki** [comment]
> 只今 PR できるところについてはこちらでやり取りされています。
> nodejs/code-and-learn#58

おっと、そんなところでやってたのね。 じゃそちらに参戦します。ありがとうございます。
結局資料は必要ないのかな。

**Comment by tgfjt** [comment]
いや～日本語の資料はありがたいですよ〜

**Comment by shigeki** [comment]
では、初日参加する人が何するかわかるよう事前に資料を伝えて、やることを知っておいたもらったほうがいいかなと思っているんですが、どうですかね？

**Comment by tgfjt** [comment]
当日は時間が短いので、そのほうが誰に対しても良さそうに思います:+1:

**Comment by sotayamashita** [comment]
@yoshuawuyts 

> if you need more hands; @watson, @mafintosh and me will be around and can help out 🎉

We appreciate that if you could. :smile:

**Comment by kentrino** [comment]
@sotayamashita さん、当日、業務の差し込みがはいってしまいました。。。 できましたら、途中までお手伝いさせていただきたいのですが、そのような形の参加でも可能でしょうか。ご迷惑おかけしまして申し訳ございません。よろしくお願い致します。

**Comment by sotayamashita** [comment]
@kentrino ちなみに何時から何時ごろまで参加することが可能でしょうか？

**Comment by yosuke-furukawa** [comment]
資料作成含めて僕の方でやっておきますよ。
多分、 
node のリポジトリ clone して ./configure && make -j8 && make test 
みたいな感じでパスしたらOKですが、windows環境の場合は若干面倒ですね（というかよく知らない）

**Comment by shigeki** [comment]
https://speakerdeck.com/shigeki/nodehefalse-kodogong-xian-falseshi-fang?slide=7 ここまでは書いてあるけど、 configure と vcbuild.bat は必要かな。BUILD.md を訳す手もあるけど icu の部分が多いので見送りました。

**Comment by yoshuawuyts** [comment]
@Sotayamashita yeah we'd be keen! From what I gather it's the first day of the conference right? The link on the opening post no longer resolves; if you could share the details we'll be there :grin:

**Comment by sotayamashita** [comment]
@yoshuawuyts 

> From what I gather it's the first day of the conference right?

Yes it is.

> The link on the opening post no longer resolves; if you could share the details we'll be there

I am sorry about that. I fixed it. Accoding to the [schedule](http://nodefest.jp/2016/schedule.html), 1st day is for Nodeschool, Node Discussion and so on.

**Comment by yoshuawuyts** [comment]
Rad, see you then!

**Comment by kentrino** [comment]
@sotayamashita 朝から14, 15時頃まで参加可能です！

**Comment by sotayamashita** [comment]
@shigeki
@kentrino
@dominhhai
@qsona
@abouthiroppy

他の用事がない方は明日は 10 時に Dots に来て頂ければと思います。
よろしくお願いします

**Comment by shigeki** [comment]
@sotayamashita  あー、Code and Learn は 15:45 〜だから午後から行けばいいやと思って、午前中に別の予定入れちゃったけど、10時に集合したほうがいい？

**Comment by sotayamashita** [comment]
@shigeki あっ午後からでも大丈夫です。

**Comment by shigeki** [comment]
@sotayamashita ありがとうございます。

**Comment by kentrino** [comment]
すみません、day2の会場に向かってしまい、すこし遅れます！

**Comment by qsona** [comment]
今日は午後からメンターをやらせていただき、良い経験になりました! ありがとうございました。

せっかくなので、今回気づいた点などを書き残しておきます。

ワークショップ自体に関して
- 意外と質問がこない、質問しづらい?
- テーブルごとにこちらから「何か詰まってることはありますか?」と声をかけてみると、結構質問があった。
  - 「何を質問してよいかわからないけどそれでもよければ・・」という声も
  - 直接ワークショップに関係ないが、Node.jsに関する質問とかも。
  - 雑談を振ると、参加者同士でも会話してくれるようになったりと
- 参加者がNode Schoolのワークショップをやっている時とやってない時があるので、 ちょっと声をかけにくい面もあった
- テーブルに対して声かけるのはやりやすいけど、個人には難しい => 後ろの段になってる席でやってる人には手薄になる

ワークショップの内容に関して
- learnyounodeで、詰まりやすい。特に、モジュールのところ以降。
  - 質問の意図をうまく取れていないことが多い。
    - これとか https://twitter.com/tgfjt/status/797321160287404032
  - Stream が出てくるあたりは普通に難しい

次にやってみたいなと思ったこととか
- テーブルにどんどん介入する!!
- 入りやすいように、テーブルに1つ、メンター用に席を空けておく?
- learnyounodeに関しては、詰まる前提として、全体向けに説明する時間があっても良いかもと思いました。(ex: 15:00-15:15でsection 6,7説明します、のようにタイムテーブルにのせる)

最後に: 今日は色々な方と話せて楽しかったです。ありがとうございました 🙇

**Comment by sotayamashita** [comment]
皆さんありがとうございました！！
