### ISSUE TITLE
東京Node学園祭2017 2日目：メンター募集🐢 🚀

### ISSUE THREAD

**Issue by sotayamashita** [nodeschool/tokyo#36]
# メンター絶賛募集中です :tada: :turtle: :rocket:

> このIssueは [東京Node学園祭2017 2日目](https://nodejs.connpass.com/event/70304/) のメンター募集のためのスレです。

## 詳細
- コメントを頂いたら随時追記しきます。
- イベントの規模的に、10人ほど集まると大変助かります・・・！:bow:
-  何か質問などありましたら、このスレのコメントでお気軽にお声掛け下さい

## 事前準備

**行動規範に目を通す**
[CoC](http://nodefest.jp/2017/coc.html) とは行動規範で事前に一通り読んでいただいて、当日は守っていただければと思います。

**当日やる予定のワークショップを確認する**
それから下のワークショップ達は事前にやっておくと当日スムーズにメンターが出来るかと思います。
答えが分かるのはもちろん、難易度や詰まりやすい箇所、当日されそうな質問が想定できるからです。
必須ではありません。
-  https://github.com/sethvincent/javascripting
-  https://github.com/workshopper/learnyounode
-  https://github.com/npm/how-to-npm
-  https://github.com/yosuke-furukawa/tower-of-babel
-  https://github.com/kohei-takata/learnyoureact
-  https://github.com/yosuke-furukawa/electronica

## スタッフ以外で協力していただけるメンターの方々
- [x] @saitoxu :+1:
- [x] @horihiro :+1:
- [x] @iwanaga :+1:
- [x] @Hakuyoka :+1:
- [x] @pg-ito :+1:
- [x] @morugu :+1:
- [ ] You!!

**Comment by saitoxu** [comment]
メンター希望です！よろしくお願いします。

**Comment by horihiro** [comment]
メンター、希望します。

先日のNodeschool Tokyoくらいしかメンター経験がないのですが、進め方は同じでしょうか？

あと裏の発表の聴講は可能でしょうか？
（それよりもさっさと申し込まねば。。。）

**Comment by iwanaga** [comment]
メンター希望します :sushi:

**Comment by sotayamashita** [comment]
@horihiro 

> あと裏の発表の聴講は可能でしょうか？

忙しくなければ聞きにいくことは可能です。ただ、聞きにいけないことを前提にして頂ければと思います。（前回のことを振り返るとたぶん大丈夫だと思いますが）

**Comment by Hakuyoka** [comment]
外部でのメンターは初めてなのですが、問題ないでしょうか？
予定されているワークショップ自体は全て行っています。

**Comment by sotayamashita** [comment]
@Hakuyoka 

> 予定されているワークショップ自体は全て行っています。

すばらしいです。よろしくお願い致します :bow:

**Comment by saitoxu** [comment]
すみません、質問で恐縮ですが、メンターする場合もconnpassからイベントへの応募は必要ですか？
メンターしつつ、両日とも聞けるところは聞きたいなと考えているのですが。

**Comment by sotayamashita** [comment]
@saitoxu 

> メンターする場合もconnpassからイベントへの応募は必要ですか？

不要です。

> メンターしつつ、両日とも聞けるところは聞きたいなと考えているのですが。

忙しくなければ聞きにいくことは可能です。ただ、聞きにいけないことを前提にして頂ければと思います。（前回のことを振り返るとたぶん大丈夫だと思いますが）

ref: https://github.com/nodeschool/tokyo/issues/36#issuecomment-339561479

**Comment by saitoxu** [comment]
@sotayamashita 承知しました！ありがとうございます！:bulb:

**Comment by pg-ito** [comment]
こんにちは。
東京node学園祭はここ何年か毎年参加していますが、メンターとしては初めて応募いたします。
よろしければハンズオンのメンターをお手伝いさせていただければと思います。
初めてメンターとして参加する場合の注意点等ありましたらお知らせいただけると助かります。
予定されているワークショップ自体は一通り終える予定です。
(大分前ですが以前あったものは一通りやったことはあります)
よろしくお願いいたします。

**Comment by sotayamashita** [comment]
@pg-ito 応募ありがとうございます。当日はよろしくお願い致します

**Comment by morugu** [comment]
メンター希望です！東京node学園祭は初参加になります。
ワークショップは全て終えています。
よろしくお願いいたします！

**Comment by sotayamashita** [comment]
@morugu 立候補していただきありがとうございます :bow:

**Comment by sotayamashita** [comment]
close します。みなさんありがとうございました :bow:

**Comment by pg-ito** [comment]
会場にて待機しております。本日はよろしくおねがいいたします。
