### ISSUE TITLE
行動規範の追加について

### ISSUE THREAD

**Issue by watilde** [nodeschool/tokyo#4]
nodeschoolの管理者向けのリポジトリがあることを今日知りました（今更なの、すみません
https://github.com/nodeschool/organizers

関係者は、READMEとCoCについて把握しておくと良さそうです。
特にCoCは細かい理解をした方が良いので
templateを翻訳してこのリポジトリに設置するのはいかがでしょうか。

**Comment by tai2** [comment]
https://github.com/nodeschool/nodeschool.github.io/issues/15
https://github.com/nodeschool/discussions/issues/93
ここらへんのissueとかも参考になると思います。

**Comment by sotayamashita** [comment]
@watilde 確かにドキュメントという形で @tai2 さんが挙げていただいたようなものを日本語訳しておくのは今後いろいろな人がより参加しやすくするためにいいですね。

以下の様な表を作成していま出たものを出来る人で分担してやりましょうか。日本語の翻訳フローに関しては、[AngularJSの日本語訳のwiki](https://github.com/angularjs-jp/angular.js/wiki/%E5%88%86%E6%8B%85%E8%A1%A8)が参考になると思います。

| ドキュメント | 担当者 | 状況 |
| --- | --- | --- |
| [README](https://github.com/nodeschool/organizers) |  |  |
| [tips and tricks for hosting a nodeschool event](https://github.com/nodeschool/nodeschool.github.io/issues/15) |  |  |
| [Want to run an event?](https://github.com/nodeschool/discussions/issues/93) |  |  |

**Comment by watilde** [comment]
このIssueの内容としてはコチラになるので

> 特にCoCは細かい理解をした方が良いので
> templateを翻訳してこのリポジトリに設置するのはいかがでしょうか。

これを翻訳して追加するかを決めたいところです＞＜
https://github.com/nodeschool/organizers/blob/master/codeofconduct-template.md

CoCは関係者だけではなく、参加者にも理解して頂く必要があるというのが理由です。

README, tips and ticks.., What to run...は、
各自で目を通しておくくらいで良さそうな気がしますがいかがでしょう？

**Comment by tai2** [comment]
そうですね。とくにWant to run an evnet?は全部訳すとしんどいので、最低限のレギュレーションみたいなものを作るために、CoCを翻訳して参照できるようにしておくのがいいと思います。

**Comment by watilde** [comment]
@tai2 いずれにせよ、とっても参考になりました。ありがとうございます！

**Comment by sotayamashita** [comment]
@watilde 

翻訳したほうがいいと思います。

理由は、READMEとCoCは主に主催する側の人たちが読んでおくものだと思うので日本に訳すと、今後nodeschoolに参加してくださる方やnodeschool東京以外での開催がしやすくなったりするからです。

翻訳したものはどこに置くと管理しやすいですかね？

**Comment by sotayamashita** [comment]
https://github.com/sotayamashita/organizers/tree/feature/japanese

**Comment by sotayamashita** [comment]
一旦ここでREADME部分の翻訳を始めようと思っています

https://github.com/sotayamashita/organizers/tree/feature/japanese

**Comment by watilde** [comment]
@sotayamashita この提案をPRにしてみました〜。 https://github.com/nodeschool/tokyo/pull/6

個人的な意見ですが、
メタな情報に関しては、リポジトリを分散させるよりnodeschool/tokyo以下にまとめた方が複数人で管理しやすくて良いなぁと思います。ディレクトリを増やして整理している国もあるようです！

**Comment by tgfjt** [comment]
README, CoC に地方差はなくて良いと思いますし、
nodeschool-jp のメンバーに、tokyo や osaka のメンバーも加えて、そちらでやるのはいかがでしょ？:panda_face:

**Comment by watilde** [comment]
@tgfjt たしかにそうですね :+1:

> README, CoC に地方差はなくて良いと思いますし、

今はリポジトリ固有の情報としてオーガナイザメンバー名の項目がありますが、
そこさえアレンジすれば差分なくせるかと思います。
置き場所、アレンジ含めて一旦再考とさせてください。

あわせてPRを一旦Closeしますが、必要あらばReopenお願いします :bow:

**Comment by watilde** [comment]
closeあざます！

**Comment by tgfjt** [comment]
@watilde 
Closing automatically via your commit message:)
