### ISSUE TITLE
nodeschool.ioの中にあるworkshopsの翻訳方法について

### ISSUE THREAD

**Issue by sotayamashita** [nodeschool/tokyo#5]
[nodeschoolのサイト](http://nodeschool.io/index.html)のサイトにあるワークショップの翻訳をする。

ワークショップの翻訳をする方は一旦ここで何が翻訳されていて翻訳されていないかの確認をしてください。[Wiki](https://github.com/nodeschool/tokyo/wiki/%E5%88%86%E6%8B%85%E8%A1%A8)にリストがありますので確認をお願いします。

**Comment by kohei-takata** [comment]
翻訳お手伝いしたいです！

**Comment by tgfjt** [comment]
@sotayamashita sota
learnyounode は、i18n化が出来ているので良いですが、他だと、PRの出し先がないですよね :crying_cat_face: 

Forkして、xxx-jp みたいに npm モジュールとして管理していく感じですか？

javascripting-jp は既にありますねー
https://github.com/ledsun/javascripting

**Comment by sotayamashita** [comment]
@tako-black ありがとうございます！翻訳を開始するまえにどうやって開発していけばいいかを考えたいです。なにかアイデア等ありますか？

**Comment by sotayamashita** [comment]
@tgfjt 

> Forkして、xxx-jp みたいに npm モジュールとして管理していく感じですか？

そう考えていました。

> javascripting-jp は既にありますねー

ありがとうございました

**Comment by tgfjt** [comment]
個人Forkでも良いとは思うのですが、管理コストで見ると、
例えば、nodeschool-jp とかでメンバーで管理出来ると良いのかなーと思いました。
https://github.com/iojs-jp/ みたいな。

**Comment by kohei-takata** [comment]
既にある javascripting-jp に従うと、個人Forkになるのかなと思いました。
ただ、グループで管理したほうがいいですよね。。。

**Comment by tgfjt** [comment]
最終的には、learnyounode のように、本家が i18n対応をしてもらえればベストとは思います。
ただ、使っている、workshopperのバージョンや、adventureだったりもするので簡単ではないですね…

個人Forkが悪いわけじゃないので、そんなに強い意思があるわけじゃないです。
翻訳 だけで言えば、なんでもいいから進めましょう、が良いかもですしね。
ただ、本家への追従だったり修正が個人に依るのも大変だったりするので。

CC:
@ledsun

**Comment by ledsun** [comment]
Forkすると本家への追従が（実質）できなくなるで、長期的によくないと思います。
javascripting-jpはすぐに欲しかったので、Forkしました。

一方、workshopperへの置き換えは、workshopperのドキュメントが無く辛いです。
すぐに着手するならForkが現実的だと思います。

管理はグループでした方が、「メンテナンスが継続される」安心感があると思います。
個人的にも嬉しいです。

workshopper化を個人で進めるのは辛いので
workshopper化ハッカソンをやるのも面白いんじゃないかと、思います。

**Comment by tai2** [comment]
workshopperの使い方は、古いのですがブログ書いてくれてる人がいますね。http://lin-clark.com/blog/2014/07/01/authoring-nodejs-workshopper-lessons/

ただ、これ1系なので、i18n対応もないし、構造も2系と違う部分があります。

learnyounodeとかが2系の使い方のサンプルになると思うので、それ見て解析して、adventureベースのやつを移植っていうのは、できるとは思います。ハッカソンもたのしそうですね。

が、ひとつ気になってることがあって、ハッカソンなどやるとして、目的としては、workshopperに置き換えた上で、PR作成してupstreamに取り込んでもらうことになるかと思います。

ただ、adventureベースでワークショップ作ってる人は、workshopperとadventureっていう2つの選択肢があった上で、あえてadventure(フルAPI形式の設計)を選択したわけですよね。それで、workshopperに置き換えたよって言って、採用してくれるのかなあというのをちょっと懸念してます。workshopper1系を使ってるやつを、2系対応にしたよっていうPRは、ぜんぜんアリだと思います。

個人的には、現状あるNodeSchoolワークショップがすべてi18n対応するのを待つよりは、断片化やむなしで日本語化しちゃったほうがいいのかなという気がしてます。ワークショップ自体、性質上そんなに進化の激しいものではないと思いますし。

**Comment by tgfjt** [comment]
確かに。
adventureベースのを置き換えるなら先に作成者に聞いてみるのもありますね。

nodeschool-jp とかで、Organization を作って、そこで xxx-jp を作って運営するのが良さそうですね。
4/12（でしたっけ）に必要な Workshop があれば、それから翻訳する感じでしょうか。

**Comment by sotayamashita** [comment]
@tgfjt @ledsun @tako-black @tai2 

それではnodeschool-jpというグループを作成してそこで翻訳作業を進めていくというやり方でいいですかね？

**Comment by tai2** [comment]
@sotayamashita :+1:

**Comment by tgfjt** [comment]
:+1:

**Comment by kohei-takata** [comment]
:+1:

**Comment by ledsun** [comment]
:+1:

**Comment by sotayamashita** [comment]
organizationを作成して皆さんを招待させていただきました。次回からnodeschoolのワークショップの翻訳は以下のorganizationでforkして行います。

https://github.com/nodeschool-jp
