### ISSUE TITLE
give us a awesome logo!

### ISSUE THREAD

**Issue by tgfjt** [nodeschool/tokyo#9]
@yosuke-furukawa

あの素敵なロゴ画像、提供頂けないでしょうか。
サイトで使えたら良いなと思います :smile_cat: 
http://nodeschool.io/tokyo/

**Comment by yosuke-furukawa** [comment]
もちろん使ってもいいですよー
aiとかpsdのイメージがほしいという話であれば、また別途渡し方を検討します！

![shibuya_node_white_800](https://cloud.githubusercontent.com/assets/555645/7000123/0352bb1c-dc56-11e4-8623-e46f939111c1.png)

**Comment by tgfjt** [comment]
ありがとうございます！
今のところ ai 等は大丈夫です。
